#!/bin/bash

ADB_BIN=${BASH_SOURCE[0]}.orig

if [[ ! -x $ADB_BIN ]];then
  echo "$ADB_BIN is not exist"
  exit -1
fi

if [[ -v SSH_CLIENT ]];then
  HOST_IP=${SSH_CLIENT%% *}
  if nc -zw1 $HOST_IP 5037 2>&1 >/dev/null  ;then
    # Host opened 5037 port
    ADB_HOST="-H $HOST_IP"
    echo -e "Remote ADB server : \033[91;1m$HOST_IP\033[0m"
  else
    echo "Host $HOST_IP is not offering adb-server"
    exit -1
  fi
fi

exec $ADB_BIN $ADB_HOST "$@"
