#!/bin/bash

ADB_BIN=$(which adb)

if [[ ! -x $ADB_BIN ]];then
  echo "$ADB_BIN is not exist"
  exit -1
fi

if [[ -v SSH_CLIENT ]];then
  HOST_IP=${SSH_CLIENT%% *}
  if nc -zw1 $HOST_IP 5037 2>&1 >/dev/null  ;then
    # Host opened 5037 port
    ADB_HOST="-H $HOST_IP"
    echo -e "Remote ADB server : \033[91;1m$HOST_IP\033[0m" 1>&2
  else
    echo "Host $HOST_IP is not offering adb-server"
    exit -1
  fi
fi

function adb-dumpui()
{
  if [[ $(adb shell pm list packages com.github.uiautomator | wc -l) != 2 ]];
  then
    echo "Helper package(s) are not installed. Installing them" >&2
    for p in $__bashrc_dir/tools/app-uiautomator*.apk;do
      adb install -r -t -g $p;
    done
  fi

  read -r -d '' shell_cmd <<SCRIPT
ps | grep com.github.uiautomator 2>&- >&- ||
  am instrument -w com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner >&- 2>&-
SCRIPT
  adb shell "$shell_cmd" &
  read -r -d '' shell_cmd <<SCRIPT
while ! ps | grep com.github.uiautomator 2>&- >&-;do sleep 1;done;
curl http://localhost:9008/jsonrpc/0 -sd '{"jsonrpc":"2.0","method":"dumpWindowHierarchy","params":[false],"id":2}'
SCRIPT
  exec adb shell $shell_cmd | jq -r .result -
  exit $?
}

case ${1} in
  logcat)
    # Append color option only when STDOUT(1) is not redirected
    [[ -t 1 ]] && ADDITIONAL_OPTIONS="-v color"
    ;;
  dumpui)
    adb-dumpui "$@"
    ;;
  tap)
    declare -a coords=()
    for elem in "${@#$1}";do
      [[ -z $elem ]] && continue;
      coords[${#coords[@]}]=$($BASH_SOURCE dumpui |\
        xmllint --xpath "translate(substring-before(substring-after(//node[@text='$elem']/@bounds, '['), ']'), ',', ' ')" -);
    done

    [[ ${#coords[@]} > 0 ]] || exit 1
    declare cmds;
    for c in "${coords[@]}";do
      cmds+="input $1 $c && ";
    done
    cmds="${cmds% && }";

    exec $ADB_BIN $ADB_HOST shell -- $cmds;;
esac

exec -a adb $ADB_BIN $ADB_HOST $1 $ADDITIONAL_OPTIONS ${@#$1}
